# This config file is for settings that affect the whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: This is Katie's personal website.
description: > # this means to ignore newlines
  Hey, this is still a work in progress. The current version is
  extremely unaesthetic. Check back in a month or so.

email: katiehdunn@gmail.com
baseurl: ""       # the subpath of your site, e.g. /blog
url: ""           # the base hostname & protocol for your site, e.g. http://example.com


# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
khd-theme:
  date_format: "%b %-d, %Y"

# Build settings
remote_theme: opalesce/opalesce.github.io
markdown: kramdown
mathjax: true

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md
 - books.md
 - contact.md

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-github-metadata
  - jekyll-feed
